// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmdRm68L4A-oJzf7X2dWqynquO8udxzSw',
    appId: '1:586544867504:web:68e48ca3ac1419af3d3375',
    messagingSenderId: '586544867504',
    projectId: 'geztek-17441',
    authDomain: 'geztek-17441.firebaseapp.com',
    databaseURL: 'https://geztek-17441-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geztek-17441.firebasestorage.app',
    measurementId: 'G-4P7GJCVLHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0jWLem45ypilhTanknqxAaTNJ531Yt-U',
    appId: '1:586544867504:android:5d83ed2745ba37973d3375',
    messagingSenderId: '586544867504',
    projectId: 'geztek-17441',
    databaseURL: 'https://geztek-17441-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geztek-17441.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1nSs69t6qynSu7i7j2rOxNNbLDsNZgt0',
    appId: '1:586544867504:ios:c99f2dfe4c193a353d3375',
    messagingSenderId: '586544867504',
    projectId: 'geztek-17441',
    databaseURL: 'https://geztek-17441-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geztek-17441.firebasestorage.app',
    iosBundleId: 'com.geztek2.geztek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1nSs69t6qynSu7i7j2rOxNNbLDsNZgt0',
    appId: '1:586544867504:ios:c99f2dfe4c193a353d3375',
    messagingSenderId: '586544867504',
    projectId: 'geztek-17441',
    databaseURL: 'https://geztek-17441-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geztek-17441.firebasestorage.app',
    iosBundleId: 'com.geztek2.geztek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmdRm68L4A-oJzf7X2dWqynquO8udxzSw',
    appId: '1:586544867504:web:7eadb2303b0978793d3375',
    messagingSenderId: '586544867504',
    projectId: 'geztek-17441',
    authDomain: 'geztek-17441.firebaseapp.com',
    databaseURL: 'https://geztek-17441-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'geztek-17441.firebasestorage.app',
    measurementId: 'G-M4B3S8791E',
  );
}
